# Generated by Django 5.2 on 2025-04-13 14:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('resolved', 'Решен'), ('closed', 'Закрыт')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Тикет',
                'verbose_name_plural': 'Тикеты',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Номер транспорта')),
                ('type', models.CharField(max_length=50, verbose_name='Тип транспорта')),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Грузоподъемность')),
                ('current_location', models.CharField(max_length=200, verbose_name='Текущее местоположение')),
                ('status', models.CharField(choices=[('loading', 'В загрузке'), ('in_transit', 'В пути'), ('customs', 'На таможне'), ('delivered', 'Доставлен'), ('delayed', 'Задержка'), ('cancelled', 'Отменен')], default='loading', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Транспорт',
                'verbose_name_plural': 'Транспорт',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('description', models.TextField(verbose_name='Описание')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Базовая цена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='transport.category')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='PriceModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название модификатора')),
                ('price_adjustment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Корректировка цены')),
                ('is_percentage', models.BooleanField(default=False, verbose_name='Процентная корректировка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_modifiers', to='transport.product')),
            ],
            options={
                'verbose_name': 'Модификатор цены',
                'verbose_name_plural': 'Модификаторы цен',
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_staff', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='transport.supportticket')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='supportticket',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='transport.transport'),
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание груза')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Объем')),
                ('sender', models.CharField(max_length=200, verbose_name='Отправитель')),
                ('receiver', models.CharField(max_length=200, verbose_name='Получатель')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargoes', to='transport.transport', verbose_name='Транспорт')),
            ],
            options={
                'verbose_name': 'Груз',
                'verbose_name_plural': 'Грузы',
            },
        ),
        migrations.CreateModel(
            name='TransportStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('loading', 'В загрузке'), ('in_transit', 'В пути'), ('customs', 'На таможне'), ('delivered', 'Доставлен'), ('delayed', 'Задержка'), ('cancelled', 'Отменен')], max_length=20, verbose_name='Статус')),
                ('location', models.CharField(max_length=200, verbose_name='Местоположение')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='transport.transport', verbose_name='Транспорт')),
            ],
            options={
                'verbose_name': 'История статуса',
                'verbose_name_plural': 'История статусов',
                'ordering': ['-timestamp'],
            },
        ),
    ]
